spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/snapguide
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        spring.jpa.properties.hibernate.use_sql_comments: true
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: your-client-id
#            client-secret: your-client-secret
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
#            scope: profile, email

#  thymeleaf:
#    enabled: false
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace

google:
  maps:
    api:
      key: AIzaSyC4A8g9EEFIPxc0GT09-Ibw7G9DMxeEwqA