spring:
  config:
    activate:
      on-profile: "local"

  myapp:
    frontend-redirect-url: http://localhost:8080
    app-redirect-uri: snapguide://oauth/callback

   # 기본 포트 8080 사용할꺼기에, 포트 정보 생략
  server:
    port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/snapguidedb
    username: postgres
    password: 5418
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        spring.jpa.properties.hibernate.use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1054453650839-fcku1a78a83p0739eb3mcv76pidtqlm0.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:/Users/kim-yeonjae/Desktop/Study/snapguide/uploads/
logging:
  level:
    org.hibernate.SQL: debug

# Local development configurations
jwt:
  access-token-expiration: 1800000 # 30min
  refresh-token-expiration: 604800000 # 1week
  secret: f9f7ca2a630ed19e8c21f3d97b5afa3e890b497ea1526e4ca80809c365b9b3f76c1aa7c548b73e06a7cddb53629ec54068372ccaa34287769116c8bc29661904

google:
  maps:
    api:
      key: AIzaSyC4A8g9EEFIPxc0GT09-Ibw7G9DMxeEwqA

storage:
  type: local
  local:
    base-dir: /Users/kim-yeonjae/Desktop/Study/snapguide/uploads
  nas:
    mount-dir: /mnt/nas/snapguide

cloud:
  aws:
    credentials:
      access-key: AKIASV6SZK4NLWRR27O3
      secret-key: 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
    s3:
      bucket: snapguide-bucket
    region:
      static: us-east-2
    stack:
      auto: false